USE instagreen;
ALTER TABLE posts ADD user_id INT UNSIGNED NOT NULL DEFAULT 0;
ALTER TABLE posts ADD FOREIGN KEY (user_id) REFERENCES users(id);

ALTER TABLE comments ADD user_id INT UNSIGNED NOT NULL DEFAULT 0;
ALTER TABLE comments ADD FOREIGN KEY (user_id) REFERENCES users(id);

ALTER TABLE comments ADD post_id INT UNSIGNED NOT NULL DEFAULT 0;
ALTER TABLE comments ADD FOREIGN KEY (post_id) REFERENCES posts(id);

ALTER TABLE likes ADD post_id INT UNSIGNED NOT NULL DEFAULT 0;
ALTER TABLE likes ADD FOREIGN KEY (post_id) REFERENCES posts(id);

ALTER TABLE likes ADD user_id INT UNSIGNED NOT NULL DEFAULT 0;
ALTER TABLE likes ADD FOREIGN KEY (user_id) REFERENCES users(id);

ALTER TABLE user_target_relation ADD user_id INT UNSIGNED NOT NULL DEFAULT 0;
ALTER TABLE user_target_relation ADD FOREIGN KEY (user_id) REFERENCES users(id);

ALTER TABLE user_target_relation ADD target_id INT UNSIGNED NOT NULL DEFAULT 0;
ALTER TABLE user_target_relation ADD FOREIGN KEY (target_id) REFERENCES users(id);